sudo: false

language: node_js

node_js:
  - "8.11.2"


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.5
    packages:
      - clang-3.5


before_install:
  # cloud-init breaks updates sometimes and we don't need it anyways
  - if [[ $(uname -s) == 'Linux' ]]; then
       export CXX="clang++-3.5";
       export CC="clang-3.5";
    fi;
  - npm install -g npm@5.6.0
  # prepare software rendering
  - sudo apt-get -y update
  - sudo apt-get -y remove cloud-init
  - sudo apt-get -y install mesa-utils
  - sudo apt-get -y install libgl1-mesa-swx11
  - sudo apt-get -y install libgl1-mesa-swx11-dev
  - sudo apt-get -y install xvfb
  - export DISPLAY=:99
  - export LIBGL_ALWAYS_SOFTWARE=1
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid
    --make-pidfile --background --exec /usr/bin/Xvfb --
    :99 -screen 0 1400x900x24 -ac +extension GLX +render


install:
  - npm i --clang=1
  - cd test && npm i --clang=1
  - cd ..


script:
  - cd test && npm test
  - cd ..
