name: Validate

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Validate:
    strategy:
        matrix:
          os: [ubuntu-16.04, windows-latest, macos-10.15]

    runs-on: ${{ matrix.os }}

    steps:

      - name: Fetch Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.16.0

      - name: Install Modules
        run: npm ci

      - name: Run Lint
        run: npm run eslint

      - name: Use opengl32.dll
        if: matrix.os == 'windows-latest'
        shell: cmd
        run: ci\windows-init.cmd

      - name: Run Unit Tests Linux
        if: matrix.os == 'ubuntu-16.04'
        run: xvfb-run --auto-servernum && npm run test-ci

      - name: Run Unit Tests Non-Linux
        if: matrix.os != 'ubuntu-16.04'
        run: npm run test-ci
